name: Early cancel
on:
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  simulate-long-running-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Starting job"
      - run: sleep 600
      - run: echo "Job finished"

